title: My Jekyll Site
description: A simple site powered by Jekyll
theme: minima
title: Cansu's Portfolio  
description: A simple site powered by Jekyll  
theme: minima  

author:
  name: Cansu

social_links:
  github: https://github.com/CansuTFG
 
